# config.py

# === MOEA/D Algorithm Parameters ===
POPULATION_SIZE = 50
NUM_GENERATIONS = 100
NEIGHBORHOOD_SIZE = 20
INITIAL_MUTATION_RATE = 0.3
MIN_MUTATION_RATE = 0.05
DIVERSITY_THRESHOLD = 3
DIVERSITY_ACCEPTANCE_PROB = 0.1
